project:
  type: book

book:
  title: "Functional Programming Notes"
  author: "Igor Dimitrov"
  date: "12/18/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Logo"
      chapters: 
      - logo/intro.qmd
  downloads: ["pdf"]
  page-navigation: true

# bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    number-depth: 1



